package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Iniciar_sesion_ventanas extends VerticalLayout {
	protected Label iniciar_sesion;
	protected TextField email;
	protected PasswordField contrasena;
	protected CheckBox recordar_contrasena;
	protected Link recuperar_contrasena;
	protected Button atras;
	protected Button iniciar;

	public Iniciar_sesion_ventanas() {
		Design.read(this);
	}
}
