package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Listas_reproduccion_propias_ventanas extends Panel {
	protected Label lista_reproducion;
	protected TextField buscarLista;
	protected Button buscar;
	protected Button lista12;
	protected Label lista1;
	protected Button modificar;
	protected Button eliminar;
	protected Button lista2;
	protected Label lista21;
	protected Button modificar1;
	protected Button eliminar1;
	protected Button lista3;
	protected Label lista31;
	protected Button modificar2;
	protected Button eliminar2;

	public Listas_reproduccion_propias_ventanas() {
		Design.read(this);
	}
}
