package Diagrama_de_clases;

public class Perfil_administrador {
	public Zona_inicio_cabecera_administrador _unnamed_Zona_inicio_cabecera_administrador_;
	public Zona_cabecera_video_administrador _unnamed_Zona_cabecera_video_administrador_;
	public Zona_cabecera_administrador _unnamed_Zona_cabecera_administrador_;
	public Zona_opciones_administrador _unnamed_Zona_opciones_administrador_;
}