package Diagrama_de_clases;

public class Perfil_registrado {
	public Zona_cabecera_video_registrado _unnamed_Zona_cabecera_video_registrado_;
	public Zona_cabecera_video_propietario _unnamed_Zona_cabecera_video_propietario_;
	public Zona_inicio_cabecera_registrado _unnamed_Zona_inicio_cabecera_registrado_;
	public Zona_cabecera_perfli_Registrado _unnamed_Zona_cabecera_perfli_Registrado_;
	public Zona_opciones_perfil_registrado _unnamed_Zona_opciones_perfil_registrado_;
	public Zona_cuerpo_perfil_registrado _unnamed_Zona_cuerpo_perfil_registrado_;
}