package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Zona_opciones_perfil_registrado_ventanas extends VerticalLayout {
	protected Label nombre_usuario;
	protected Link inicio;
	protected Link subir_video;
	protected Link modificar_datos;
	protected Link cambiar_contrasena;
	protected Link historial;
	protected Link videos_ultimos_subidos;
	protected Link cerrar_sesion;

	public Zona_opciones_perfil_registrado_ventanas() {
		Design.read(this);
	}
}
